api:
  replicas: 1
  image: samarabdelaziz/flask-api
  tag: latest
  containerport: 3000
  resources:
    requests:
      memory: 128Mi
      cpu: 100m
    limits:
      memory: 256Mi
      cpu: 200m